version: "3.8"
services:
  webserver:
    hostname: webserver
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
    - "80:80"
    depends_on:
    - db

  db:
    image: postgres:14
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=practice_db_1
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

volumes:
  source_code:
#volumes:
#  mysql_data: { driver: local }

